//COMMON USED
export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';
//POSTS
export const FETCH_POST = 'FETCH_POST';
export const LIKE = 'LIKE';
export const FETCH_POST_USER = 'FETCH_POST_USER';

//AUTH
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

//USERS
export const FETCH_USER = 'FETCH_USER';
export const FETCH_ALL_USER = 'FETCH_ALL_USER';

//FriendRequest
export const FETCH_REQUEST_USER = 'FETCH_REQUEST_USER';
export const FETCH_ALL_REQUEST = 'FETCH_ALL_REQUEST';
export const FETCH_RESPONSE_USER = 'FETCH_RESPONSE_USER';

//COMMENTS
export const FETCH_COMMENT_POST = 'FETCH_COMMENT_POST';

//Chat
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_MESSAGES = 'SET_MESSAGES';

//SEARCH
export const FETCH_SEARCH_USER = 'FETCH_SEARCH_USER';
export const FETCH_ALL_SEARCH = 'FETCH_ALL_SEARCH';

//REACTIONS
export const FETCH_ALL_LIKE = 'FETCH_ALL_LIKE';
export const FETCH_POST_LIKE = 'FETCH_POST_LIKE';
export const FETCH_COMMENT_LIKE = 'FETCH_COMMENT_LIKE';
export const CREATE_LIKE = 'CREATE_LIKE';
export const UPDATE_LIKE = 'UPDATE_LIKE';
export const DELETE_LIKE = 'DELETE_LIKE';

//NOTIFICATIONS
export const FETCH_NOTIFICATION_USER = 'FETCH_NOTIFICATION_USER';
export const FETCH_NOTIFICATION = 'FETCH_NOTIFICATION';

//CHAT
export const FETCH_MESSAGE_ROOM = 'FETCH_MESSAGE_ROOM';
export const FETCH_ROOM = 'FETCH_ROOM';